---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: gluster-database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  template:
    spec:
      containers:
        - name: cockroachdb
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  template:
    spec:
      containers:
        - name: cockroachdb
          command:
            - "/bin/bash"
            - "-ecx"
            - |
              install --directory --mode 0700 /tmp/cockroach-certs && \
              cp /cockroach/cockroach-certs/* /tmp/cockroach-certs/ && \
              chown -R "$(id -u):0" /tmp/cockroach-certs && \
              chmod 0400 /tmp/cockroach-certs/* && \
              exec /cockroach/cockroach start --logtostderr --certs-dir /tmp/cockroach-certs --advertise-host $(hostname -f) --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%
