---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mhu-infra
commonLabels:
  app: cockroachdb
resources:
  - cockroachdb-statefulset.yaml
patchesStrategicMerge:
  - cockroachdb-patches.yaml
