---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mhu-infra
commonLabels:
  app: cockroachdb
resources:
  - cockroachdb-statefulset.yaml
patchesStrategicMerge:
  - set_pvc_size.yml
  - set_resources.yml
  - secret_permission_hack.yml
