---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: gluster-database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
